import '@styles/globals.css';

import { Lexend } from 'next/font/google'
import Nav from '@components/nav';

const lexend = Lexend({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
